apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "cicd-tools",
      "kind": "DeploymentConfig"}]'
  name: rhforum-pipeline
spec:
  source:
    git:
      ref: master
      uri: https://github.com/guaxinim/rh-forum.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
